name = "dashchat"
compatibility_date = "2022-06-01"
main = "dist/worker.js"
workers_dev = false

route = {pattern = "https://api.dashchat.app/*", zone_name = "dashchat.app"}

kv_namespaces = [
  {binding = "KV", id = "b67bf7eb75f64392b0c3d7fef8e63079"}
]

[durable_objects]
bindings = [
  {name = "ROOMS", class_name = "Room"},
  {name = "ANALYTICS",class_name = "Analytics"}
]

[[migrations]]
tag = "initialization"
new_classes = ["Room", "Analytics"]