name = "dashchat"
compatibility_date = "2022-06-01"
compatibility_flags = ["durable_object_alarms"]
main = "dist/worker.js"
workers_dev = false

route = {pattern = "https://api.dashchat.app/*", zone_name = "dashchat.app"}

kv_namespaces = [
  {binding = "KV", id = "714a56880545489ebee9ccc5209f116c"}
]

[durable_objects]
bindings = [
  {name = "ROOMS", class_name = "Room"}
]

[[migrations]]
tag = "initialization"
new_classes = ["Room", "Analytics"]

[[migrations]]
tag = "delete_analytics"
deleted_classes = ["Analytics"]

[[migrations]]
tag = "remove_alarms_part_1"
deleted_classes = ["Room"]

[[migrations]]
tag = "remove_alarms_part_2"
new_classes = ["Room"]